### ISSUE TITLE
Link function now spinning up local host

### ISSUE THREAD

**Issue by tonytusharjr** [evanphilipsmith/gsheets-plaid#5]
Hi Evan,
I attempted to follow along with what you've shared here. When I get to the link step I cannot get it to work. Here's the start of the output in terminal that I see:
``` (gsheets-plaid) tonytusharjr@tonys-air gsheets-plaid % python3 -m gsheets_plaid link
['/usr/local/bin/npm', 'start']

> plaid-tiny-quickstart@1.0.0 start
> node server.js

(node:83713) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/tonytusharjr/Virtualenvs/gsheets-plaid/lib/python3.10/site-packages/gsheets_plaid/resources/plaid_link_server/node_modules/axios/lib/core/createError.js:16
  var error = new Error(message);
              ^

Error: Request failed with status code 400
    at createError (/Users/tonytusharjr/Virtualenvs/gsheets-plaid/lib/python3.10/site-packages/gsheets_plaid/resources/plaid_link_server/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/tonytusharjr/Virtualenvs/gsheets-plaid/lib/python3.10/site-packages/gsheets_plaid/resources/plaid_link_server/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/tonytusharjr/Virtualenvs/gsheets-plaid/lib/python3.10/site-packages/gsheets_plaid/resources/plaid_link_server/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1344:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  config: {
    url: 'https://sandbox.plaid.com/link/token/create',
    method: 'post',
    data: `{"user":{"client_user_id":"..."},"client_name":"Plaid's Tiny Quickstart","language":"en","products":["transactions"],"country_codes":["US"],"redirect_uri":"https://localhost:8080/oauth"}`,
```
Any advice on this would be appreciated. Thanks for building this!

**Comment by evanphilipsmith** [comment]
Hi @tonytusharjr! Thanks for checking out my project.

I'm not sure what the issue is here, but I'm guessing it has something to do with the way the Plaid Link server is configured. I had just pushed up the `node_modules` directory into the repository and hoped that would work, but it seemed a little hacky to me. #2 was dedicated to coming up with a replacement to this.

I went ahead and implemented a new, simpler Plaid Link server that uses Flask (so now NodeJS is no longer a prerequisite, and #2 is closed). I just released v0.0.4 with this new Link server, so try upgrading `gsheets-plaid` and see if that works for you.
```
pip install -U gsheets-plaid
```

**Comment by tonytusharjr** [comment]
@evanphilipsmith Thanks for reviewing this issue and creating v0.0.4! This time when I ran the link command I was successfully prompted through the Google auth flow, however the Plaid flow is failing. I'll try to mess around with this when I have time, but wanted to share this with you as well:

```
plaid.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Server': 'nginx', 'Date': 'Wed, 11 May 2022 02:54:05 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '322', 'Connection': 'keep-alive'})
HTTP response body: {
  "display_message": null,
  "documentation_url": "https://plaid.com/docs/?ref=error#invalid-request-errors",
  "error_code": "INVALID_FIELD",
  "error_message": "client_id must be a properly formatted, non-empty string",
  "error_type": "INVALID_REQUEST",
  "request_id": "UsfS7Y93Xget2Sg",
  "suggested_action": null
}
```

**Comment by tonytusharjr** [comment]
I checked init command again and realized it dropped my client_id. After re configuring that I get this error:
```
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Server': 'nginx', 'Date': 'Wed, 11 May 2022 02:58:56 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '351', 'Connection': 'keep-alive', 'plaid-version': '2020-09-14'})
HTTP response body: {
  "display_message": null,
  "documentation_url": "https://plaid.com/docs/?ref=error#invalid-request-errors",
  "error_code": "INVALID_FIELD",
  "error_message": "OAuth redirect URI must be configured in the developer dashboard. See https://plaid.com/docs/#oauth-redirect-uris",
  "error_type": "INVALID_REQUEST",
  "request_id": "2rpTxxuSZrEfHOW"
}
```
Do we need to have this config'd for OAUTH?

**Comment by evanphilipsmith** [comment]
Ah, good catch there. Yeah I forgot to add the step for configuring the OAuth redirect URI in the Plaid dashboard to the README. I'm not sure it is necessary for the purposes of this type of project, but since the [Plaid documentation](https://plaid.com/docs/link/oauth/#introduction-to-oauth) says it's required, I have it set up that way.

> OAuth support is required in all Plaid integrations. Without OAuth support, your end users will not be able to connect accounts from institutions that require OAuth. This guide demonstrates how to implement OAuth in your Plaid integration.

It's a pretty straightforward process though. Just go to the API menu in Team Settings (quick link [here](https://dashboard.plaid.com/team/api)) and add `https://localhost:8080/oauth` to the list of Redirect URIs. In my experience, the change takes effect pretty much immediately.

(I'll add this to the README)

**Comment by tonytusharjr** [comment]
@evanphilipsmith - This is getting closer, but there's still an issue.
I can get through the Plaid UI and link a sandbox bank account with the typical credentials. After that completes and I get the link complete, I click to continue and then get the internal server error. The traceback says:
``` FileNotFoundError: [Errno 2] No such file or directory: '/Users/tonytusharjr/Virtualenvs/gsheets-plaid/lib/python3.10/site-packages/gsheets_plaid/resources/db/tokens/plaid_tokens.json'```

![image](https://user-images.githubusercontent.com/34496695/167980571-3326b401-2c0d-43c8-93e4-9aefcf924207.png)

Should there be a plaid_tokens.json file written to the resources/db/tokens folder?

**Comment by evanphilipsmith** [comment]
Yes, another good catch. When I created the new Plaid Link server, I forgot to add the logic that creates a new token file if one does not exist 🙃 

I just published v0.0.5 with the fix

**Comment by evanphilipsmith** [comment]
@tonytusharjr were you able to get it working?

**Comment by tonytusharjr** [comment]
I could not. Thanks for your help though!

**Comment by evanphilipsmith** [comment]
@tonytusharjr I have made some updates in the last few months, if you are still interested in the project feel free to install the latest version and follow the updated tutorial 🙂
